---
- name: Sample Ping Rulebook
  hosts: localhost
  sources:
    - ansible.eda.generic:
        payload:
          message: "trigger"
  rules:
    - name: Run ping when triggered
      condition: event.message == "trigger"
      action:
        debug:
          msg: "Test rulebook"
