---
- name: Sample Ping Rulebook
  hosts: localhost
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: Run ping when triggered
      condition: event.i == 1
      action:
        debug:
          msg: "Test rulebook"
