---
- hosts: localhost
  gather_facts: False
  collections:
     - hpe.oneview
  tasks:
    - name: Add a server to OneView
      oneview_server_hardware:
        hostname: "{{ oneview_ip }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_passwd }}"
        state: present
        data:
           hostname : '{{ ilo_ip }}'
           username : '{{ ilo_user }}'
           password : '{{ ilo_password }}'
           licensingIntent: "OneView"
           configurationState: "Managed"
           #force: true
      register: add_result

    - name: Result
      debug:
        msg: "{{ add_result }}"
