---
- hosts: localhost
  gather_facts: False
  collections:
     - hpe.oneview
  tasks:
    - name: Get existing server hardwares from OneView
      oneview_server_hardware_facts:
        hostname: "{{ oneview_ip }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_passwd }}"
      delegate_to: localhost
